CREATE TABLE "words" (
	"word_type"				TEXT	CHECK(word_type IN ("std", "i_adj", "na_adj", "ru_verb", "u_verb", "irr_verb")) NOT NULL,
	"lesson"				INTEGER,
	"kana"					TEXT 	NOT NULL,
	"english"				TEXT 	NOT NULL,
	"kanji"					TEXT,
	"kana_pres_aff"			TEXT,
	"kana_pres_neg"			TEXT,
	"kana_past_aff"			TEXT,
	"kana_past_neg"			TEXT,
	"kana_short_pres_aff"	TEXT,
	"kana_short_pres_neg"	TEXT,
	"kana_short_past_aff"	TEXT,
	"kana_short_past_neg"	TEXT,
	"kana_te_form"			TEXT,
	"kanji_pres_aff"			TEXT,
	"kanji_pres_neg"		TEXT,
	"kanji_past_aff"			TEXT,
	"kanji_past_neg"		TEXT,
	"kanji_short_pres_aff"	TEXT,
	"kanji_short_pres_neg"	TEXT,
	"kanji_short_past_aff"	TEXT,
	"kanji_short_past_neg"	TEXT,
	"kanji_te_form"			TEXT,
	"noun_mod_form"			TEXT,
	PRIMARY KEY (kana, english, kanji)
);
